name = "hello-friend-ng-hz"
license = "MIT"
licenselink = "https://github.com/haozeke/hugo-theme-hello-friend-ng-hz/blob/master/LICENSE.md"
description = "A batteries included theme for tech blogs."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.74

[author]
  name = "Rohit Goswami"
  homepage = "https://rgoswami.me"
  twitter = "https://twitter.com/rg0swami"

[original]
  name = "hello-friend"
  homepage = "https://github.com/panr/hugo-theme-hello-friend"
  repo = "https://github.com/panr/hugo-theme-hello-friend"

[base]
  name = "hello-friend-ng"
  homepage = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
